name: gh-page

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: packages/docs

jobs:
  publish-docs-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Set NEED_PUBLISH
        run: echo "NEED_PUBLISH=$(./has-changes.sh)" >> $GITHUB_ENV

      - name: Install
        if: ${{ env.NEED_PUBLISH }}
        run: npm ci
        working-directory: .

      - name: Build
        if: ${{ env.NEED_PUBLISH }}
        run: npm run build

      - name: Deploy
        if: ${{ env.NEED_PUBLISH }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/docs/src/.vitepress/dist
          clean: true
