name: ActMaster publish npm

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: packages/act-master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      # Check if version has changed
      - name: Set NEED_PUBLISH
        run: echo "NEED_PUBLISH=$(./need-publish.sh)" >> $GITHUB_ENV

      - name: Install
        if: ${{ env.NEED_PUBLISH }}
        run: npm ci
        working-directory: .

      - name: Publish
        if: ${{ env.NEED_PUBLISH }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
